stages:
  - check
  - configure
  - destroy

variables:
  CONTAINER_URL: "stackspot/runtime-job-destroy:latest"
  LOCALEXEC_ENABLED: "false"

check_runner:
  stage: check
  script:
    - echo "🤖 OS runner is $(uname)"

configure_aws_credentials:
  stage: configure
  script:
    - if [ -n "$AWS_ROLE_ARN" ]; then
        aws sts assume-role --role-arn $AWS_ROLE_ARN --role-session-name gitlab-ci-session > /tmp/creds.json;
        export AWS_ACCESS_KEY_ID=$(cat /tmp/creds.json | jq -r '.Credentials.AccessKeyId');
        export AWS_SECRET_ACCESS_KEY=$(cat /tmp/creds.json | jq -r '.Credentials.SecretAccessKey');
        export AWS_SESSION_TOKEN=$(cat /tmp/creds.json | jq -r '.Credentials.SessionToken');
      fi

run_runtime_action_destroy:
  stage: destroy
  script:
    - |
      FLAGS=$(echo "-v $CI_PROJECT_DIR:/app-volume \
      -e FEATURES_LEVEL_LOG=$FEATURES_LEVEL_LOG \
      -e AUTHENTICATE_CLIENT_ID=$CLIENT_ID \
      -e AUTHENTICATE_CLIENT_SECRET=$CLIENT_KEY \
      -e AUTHENTICATE_CLIENT_REALMS=$CLIENT_REALM \
      -e AUTHENTICATE_URL=https://idm.stackspot.com \
      -e REPOSITORY_NAME=$REPOSITORY_NAME \
      -e FEATURES_API_MANAGER=https://runtime-manager.v1.stackspot.com \
      -e FEATURES_BASEPATH_TMP=/tmp/runtime/deploys \
      -e FEATURES_BASEPATH_EBS=/opt/runtime \
      -e FEATURES_TEMPLATES_FILEPATH=/app/ \
      -e FEATURES_BASEPATH_TERRAFORM=/root/.asdf/shims/terraform \
      -e AWS_REGION=$AWS_REGION \
      -e FEATURES_RELEASE_LOCALEXEC=$LOCALEXEC_ENABLED")

      if [ -z "$AWS_ROLE_ARN" ]; then
        FLAGS=$(echo "$FLAGS -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID")
        FLAGS=$(echo "$FLAGS -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY")
        FLAGS=$(echo "$FLAGS -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN")
      fi

      if [ -n "$AWS_ROLE_ARN" ]; then
        FLAGS=$(echo "$FLAGS -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID")
        FLAGS=$(echo "$FLAGS -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY")
        FLAGS=$(echo "$FLAGS -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN")
      fi

      if [ -n "$TF_LOG_PROVIDER" ]; then
        FLAGS=$(echo "$FLAGS -e FEATURES_TERRAFORM_LOGPROVIDER=$TF_LOG_PROVIDER")
      fi

      docker run --rm \
      $FLAGS \
      -e FEATURES_TERRAFORM_MODULES='$FEATURES_TERRAFORM_MODULES' \
      --entrypoint=/app/stackspot-runtime-job-destroy \
      $CONTAINER_URL start --run-task-id="$RUN_TASK_ID"